
- name: Create a application user
  ansible.builtin.user:
    name: roboshop
    

- name : Delete old Directory
  ansible.builtin.file:
    path : /app
    state : absent

- name : Create a application directory
  ansible.builtin.file :
    path: /app
    state : directory

- name : Download Application Content 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes