- name : Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed
  
- name : Include pre_requisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Download application dependencies
  ansible.buitlin.shell: mvn clean package ; mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar
  args: 
    chdir : /app

- name : Include Systemd setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml